### ISSUE TITLE
Missing "time ./a.out" ?

### ISSUE THREAD

**Issue by denilsonsa** [fabiensanglard/dc#21]
At `cc.php`, section *LTO*, the example terminal shows first compiling with gcc, then `time ./a.out`, and afterwards compiling it again, but outputs the timing without running it. Have you forgot to add `time ./a.out` again? Did the position of `-flto` affect the output? Could you please write a small paragraph or sentence talking about the position of the parameter?

This issue is present on both `gcc` and `clang` versions of the terminal output.

As a bonus (possible) mistake, the output of `file` is exactly the same on both gcc objects, but the second one is highlighted red. Is it a mistake?

![image](https://github.com/fabiensanglard/dc/assets/121676/b698fe1d-b764-4839-9f11-fcee5849be5e)

**Comment by fabiensanglard** [comment]
Please open and issue for each issue. Having multiple issues discussed in here is confusing. 

1/ Have you forgot to add time `./a.out` again. Yes, `time ./a.out` was omitted this is now fixed in 47fe001ce3274e26fe13226265beef3512fccdef.
2/ Did the position of -flto affects the output. No it doesn't.
3/ Could you please write a small paragraph or sentence talking about the position of the parameter? I don't know what you mean. Feel free to send a PR.
